---
title: "Biodiversidad de la Gran Área Metropolitana"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
#-------------------- Paquetes --------------------

library(flexdashboard)
library(readr)
library(plotly)

#------------------- Constantes -------------------

# Año límite inferior del periodo de datos a considerar
ANYO_LIMITE_INFERIOR = "2000"

# Año límite superior del periodo de datos a considerar
ANYO_LIMITE_SUPERIOR = "2019"

#--------------- URL de geoservicios --------------

url_csv_registros_presencia <-
  "https://raw.githubusercontent.com/atlas-servicios-ecosistemicos-gam/datos-biodiversidad/main/gam/gam-registros-presencia-chordata-plantae.csv"

#--------------- Objetos df ---------------

# Registros de presencia filtrados por rango taxonómico (>= SPECIES) y año
df_registros_presencia <- 
  readr::read_csv(url_csv_registros_presencia) %>%
  filter((taxonRank == "SPECIES" | taxonRank == "SUBSPECIES" | taxonRank == "VARIETY" | taxonRank == "FORM") & year >= ANYO_LIMITE_INFERIOR & year <= ANYO_LIMITE_SUPERIOR)

# AVES
# Registros de presencia de aves
df_registros_presencia_aves <- 
  df_registros_presencia %>%
  filter(class == "Aves")

# Registros de presencia de aves agrupados por año
df_registros_presencia_aves_agrupados_por_anyo <-
  df_registros_presencia_aves %>%
  dplyr::count(year)

# Registros de presencia de aves agrupados por especie
df_registros_presencia_aves_agrupados_por_especie <-
  df_registros_presencia_aves %>%
  dplyr::count(species)

# Cantidad de registros de presencia de aves
registros_presencia_aves <- 
  nrow(df_registros_presencia_aves)

# Cantidad de especies de aves
especies_aves <-
  nrow(df_registros_presencia_aves_agrupados_por_especie)


# ANFIBIOS
# Registros de presencia de anfibios
df_registros_presencia_amphibia <- 
  df_registros_presencia %>%
  filter(class == "Amphibia")

# Registros de presencia de anfibios agrupados por año
df_registros_presencia_amphibia_agrupados_por_anyo <-
  df_registros_presencia_amphibia %>%
  dplyr::count(year)

# Registros de presencia de anfibios agrupados por especie
df_registros_presencia_amphibia_agrupados_por_especie <-
  df_registros_presencia_amphibia %>%
  dplyr::count(species)

# Cantidad de registros de presencia de anfibios
registros_presencia_amphibia <- 
  nrow(df_registros_presencia_amphibia)

# Cantidad de especies de anfibios
especies_amphibia <-
  nrow(df_registros_presencia_amphibia_agrupados_por_especie)

# REPTILES
# Registros de presencia de reptiles
df_registros_presencia_reptilia <- 
  df_registros_presencia %>%
  filter(class == "Reptilia")

# Registros de presencia de reptiles agrupados por año
df_registros_presencia_reptilia_agrupados_por_anyo <-
  df_registros_presencia_reptilia %>%
  dplyr::count(year)

# Registros de presencia de reptiles agrupados por especie
df_registros_presencia_reptilia_agrupados_por_especie <-
  df_registros_presencia_reptilia %>%
  dplyr::count(species)

# Cantidad de registros de presencia de reptiles
registros_presencia_reptilia <- 
  nrow(df_registros_presencia_reptilia)

# Cantidad de especies de reptiles
especies_reptilia <-
  nrow(df_registros_presencia_reptilia_agrupados_por_especie)


# MAMÍFEROS
# Registros de presencia de mamíferos
df_registros_presencia_mammalia <- 
  df_registros_presencia %>%
  filter(class == "Mammalia")

# Registros de presencia de mamíferos agrupados por año
df_registros_presencia_mammalia_agrupados_por_anyo <-
  df_registros_presencia_mammalia %>%
  dplyr::count(year)

# Registros de presencia de mamíferos agrupados por especie
df_registros_presencia_mammalia_agrupados_por_especie <-
  df_registros_presencia_mammalia %>%
  dplyr::count(species)

# Cantidad de registros de presencia de mamíferos
registros_presencia_mammalia <- 
  nrow(df_registros_presencia_mammalia)

# Cantidad de especies de mamíferos
especies_mammalia <-
  nrow(df_registros_presencia_mammalia_agrupados_por_especie)


# PLANTAS
# Registros de presencia de plantas
df_registros_presencia_plantae <- 
  df_registros_presencia %>%
  filter(kingdom == "Plantae")

# Registros de presencia de plantas agrupados por año
df_registros_presencia_plantae_agrupados_por_anyo <-
  df_registros_presencia_plantae %>%
  dplyr::count(year)

# Registros de presencia de plantas agrupados por especie
df_registros_presencia_plantae_agrupados_por_especie <-
  df_registros_presencia_plantae %>%
  dplyr::count(species)

# Cantidad de registros de presencia de plantas
registros_presencia_plantae <- 
  nrow(df_registros_presencia_plantae)

# Cantidad de especies de plantas
especies_plantae <-
  nrow(df_registros_presencia_plantae_agrupados_por_especie)

```

Aves
=======================================================================
Row {data-height=10}
-----------------------------------------------------------------------
### **Servicio ecosistémico de soporte: Hábitat para la biodiversidad (riqueza de especies). Fuente de los datos: [Infraestructura Global de Información en Biodiversidad (GBIF)](https://doi.org/10.15468/dl.653aqp). Se incluyen los registros de presencia de especies identificadas entre 2000 y 2019.**

Row
-----------------------------------------------------------------------

### 

```{r}

plot_ly(data = df_registros_presencia_aves_agrupados_por_anyo,
        x = ~year,
        y = ~n,
        type = "bar",
        text = ~n, textposition = 'auto') %>%
  layout(
     title = paste0("Distribución de registros de presencia de especies de aves por año (total de registros: ", registros_presencia_aves, ", total de especies: ", especies_aves, ")"),
     xaxis = list(title = "Año"),
     yaxis = list(title = "Registros de presencia")
  ) %>%
  config(locale = 'es')

```

Anfibios
=======================================================================
Row {data-height=10}
-----------------------------------------------------------------------
### **Servicio ecosistémico de soporte: Hábitat para la biodiversidad (riqueza de especies). Fuente de los datos: [Infraestructura Global de Información en Biodiversidad (GBIF)](https://doi.org/10.15468/dl.653aqp). Se incluyen los registros de presencia de especies identificadas entre 2000 y 2019.**

Row
-----------------------------------------------------------------------

### 

```{r}

plot_ly(data = df_registros_presencia_amphibia_agrupados_por_anyo,
        x = ~year,
        y = ~n,
        type = "bar",
        text = ~n, textposition = 'auto') %>%
  layout(
     title = paste0("Distribución de registros de presencia de especies de anfibios por año (total de registros: ", registros_presencia_amphibia, ", total de especies: ", especies_amphibia, ")"),
     xaxis = list(title = "Año"),
     yaxis = list(title = "Registros de presencia")
  ) %>%
  config(locale = 'es')

```

Reptiles
=======================================================================
Row {data-height=10}
-----------------------------------------------------------------------
### **Servicio ecosistémico de soporte: Hábitat para la biodiversidad (riqueza de especies). Fuente de los datos: [Infraestructura Global de Información en Biodiversidad (GBIF)](https://doi.org/10.15468/dl.653aqp). Se incluyen los registros de presencia de especies identificadas entre 2000 y 2019.**

Row
-----------------------------------------------------------------------

### 

```{r}

plot_ly(data = df_registros_presencia_reptilia_agrupados_por_anyo,
        x = ~year,
        y = ~n,
        type = "bar",
        text = ~n, textposition = 'auto') %>%
  layout(
     title = paste0("Distribución de registros de presencia de especies de reptiles por año (total de registros: ", registros_presencia_reptilia, ", total de especies: ", especies_reptilia, ")"),
     xaxis = list(title = "Año"),
     yaxis = list(title = "Registros de presencia")
  ) %>%
  config(locale = 'es')

```

Mamíferos
=======================================================================
Row {data-height=10}
-----------------------------------------------------------------------
### **Servicio ecosistémico de soporte: Hábitat para la biodiversidad (riqueza de especies). Fuente de los datos: [Infraestructura Global de Información en Biodiversidad (GBIF)](https://doi.org/10.15468/dl.653aqp). Se incluyen los registros de presencia de especies identificadas entre 2000 y 2019.**

Row
-----------------------------------------------------------------------

### 

```{r}

plot_ly(data = df_registros_presencia_mammalia_agrupados_por_anyo,
        x = ~year,
        y = ~n,
        type = "bar",
        text = ~n, textposition = 'auto') %>%
  layout(
     title = paste0("Distribución de registros de presencia de especies de mamíferos por año (total de registros: ", registros_presencia_mammalia, ", total de especies: ", especies_mammalia, ")"),
     xaxis = list(title = "Año"),
     yaxis = list(title = "Registros de presencia")
  ) %>%
  config(locale = 'es')

```

Plantas
=======================================================================
Row {data-height=10}
-----------------------------------------------------------------------
### **Servicio ecosistémico de soporte: Hábitat para la biodiversidad (riqueza de especies). Fuente de los datos: [Infraestructura Global de Información en Biodiversidad (GBIF)](https://doi.org/10.15468/dl.653aqp). Se incluyen los registros de presencia de especies identificadas entre 2000 y 2019.**

Row
-----------------------------------------------------------------------

### 

```{r}

plot_ly(data = df_registros_presencia_plantae_agrupados_por_anyo,
        x = ~year,
        y = ~n,
        type = "bar",
        text = ~n, textposition = 'auto') %>%
  layout(
     title = paste0("Distribución de registros de presencia de especies de plantas por año (total de registros: ", registros_presencia_plantae, ", total de especies: ", especies_plantae, ")"),
     xaxis = list(title = "Año"),
     yaxis = list(title = "Registros de presencia")
  ) %>%
  config(locale = 'es')

```